spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: data
  datasource:
    url: jdbc:postgresql://localhost:PORT/DB_NAME
    username: changeMe
    password: changeMe
    driverClassName: org.postgresql.Driver
  application:
    name: user-service
settings:
  email-service:
    uri: http://localhost:3333/api/v1/email
jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: Clevertec
