
spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5777/emailDB
    username: postgres
    password: Aries1994
    driverClassName: org.postgresql.Driver
  mail:
    username: clevertecnewstask@gmail.com
    password: djhxkdvoxqpurkbp

